# BeatScope: Spotify Analytics Configuration

# Data Processing Settings
data_processing:
  batch_size: 1000  # Number of tracks to process in each batch
  chunk_size: 10000  # Number of records to process in memory at once
  
# File Paths
paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  enriched_data: "data/enriched"
  results: "results"
  logs: "logs"

# Analysis Settings
analysis:
  min_listening_duration: 30000  # Minimum duration to count as a "listen" (ms)
  skip_threshold: 0.3  # Percentage of track duration to consider as "skipped"
  session_timeout: 1800000  # Time between streams to consider new session (ms)
  
# Visualization Settings
visualization:
  theme: "plotly_white"
  color_palette: "viridis"
  figure_width: 1200
  figure_height: 800
  
# Machine Learning Settings
ml:
  test_size: 0.2
  random_state: 42
  n_jobs: -1
  cv_folds: 5
  
# Dashboard Settings
dashboard:
  port: 8501
  host: "localhost"
  debug: false
  auto_reload: true
  
# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/spotify_analytics.log"
  
# Performance Settings
performance:
  use_multiprocessing: true
  max_workers: 4
  memory_limit_gb: 8
  
# Data Validation
validation:
  required_fields:
    - "ts"
    - "ms_played"
    - "track_name"
    - "artist_name"
  date_range:
    start: "2014-01-01"
    end: "2025-12-31"
